services:

  frontend:
    container_name: reactjs
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      - market-place
    depends_on:
      - postgresql

  backend:
    container_name: nodejs
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    networks:
      - market-place
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14.1-alpine
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    expose:
      - '${DB_PORT}'
    networks:
      - market-place
    volumes:
      - my-postgres-data:/var/lib/postgresql/data
networks:
  market-place:
    driver: bridge
volumes:
  my-postgres-data:
    driver: local
