services:
  frontend:
    container_name: reactjs
    image: kira2104/naha-marketplace-frontend
    ports:
      - "5432:5432"
    networks:
      - market-place
    depends_on:
      - postgresql

  backend:
    container_name: nodejs
    image: kira2104/naha-marketplace-backend
    env_file:
      - path: .env
    ports:
      - "3333:3333"
    networks:
      - market-place
    depends_on:
      - postgresql

  postgresql:
    image: postgres:14.1-alpine
    env_file:
      - path: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    expose:
      - "${DB_PORT}"
    networks:
      - market-place
    volumes:
      - my-postgres-data:/var/lib/postgresql/data
networks:
  market-place:
    driver: bridge
volumes:
  my-postgres-data:
    driver: local
